spring.application.name=LibraryProject

# Server Port
server.port=9094

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/LibraryManagementSystem
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

#logging.level.root=TRACE
# Ye likh diya to sb dikhayte ga

logging.level.com.LibraryProject=TRACE
# ye sirf apne ka dikayega upr wala sb cheez ka dikhayega console bhr dega

# Console Patter
logging.pattern.console=%d{yyyy-MM-dd} %d{HH:mm:ss} %-5level %msg%n


#Logging actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=True
info.app.author= Shishir Srivastava
info.app.version= 1.0.9.0

management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

#For Spring security
spring.security.user.name=Shishir
spring.security.user.password=123456

jwt.secret=${SECRET_KEY}

